# This file is used to debug on Visual Studio

version: '3.4'

services:
  sogigimind:
    build:
      context: .
      dockerfile: SogigiMind/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5000
    ports:
      - "5000"
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
